#Persisted GateBridge Cluster Gateway State
#Mon Jul 13 09:27:31 GMT-03:00 2026
cluster.watashi.allowedIps=127.0.0.1,0\:0\:0\:0\:0\:0\:0\:1
cluster.watashi.nodes=
cluster.watashi.rateLimitDurationSeconds=10
cluster.watashi.rateLimitRequests=10
cluster.watashi.requireToken=true
cluster.watashi.secret=general_secretKey
cluster.watashi.timeoutMs=5000
clusters.list=watashi
