# Hexacloud Framework Configurations

# Default cluster settings
cluster.default.secret=general_secretKey
cluster.default.requireToken=true
cluster.default.timeoutMs=5000
cluster.default.allowedIps=127.0.0.1,0:0:0:0:0:0:0:1
cluster.default.rateLimitRequests=10
cluster.default.rateLimitDurationSeconds=10

# Specific settings for 'watashi-00' cluster
cluster.watashi-00.secret=watashi_secretKey
cluster.watashi-00.requireToken=true
cluster.watashi-00.allowedIps=127.0.0.1,0:0:0:0:0:0:0:1
cluster.watashi-00.rateLimitRequests=3
cluster.watashi-00.rateLimitDurationSeconds=10

# Specific settings for 'test-cluster' (testing unauthenticated access)
cluster.test-cluster.secret=test_secretKey
cluster.test-cluster.requireToken=false
